### PR TITLE
Adding a command to search for a pattern in a file/standard input

### LINKED ISSUE #2: Add a command to "Search for a string/pattern within a file/standard input"
Add a cross-platform command implementation to search for a string/pattern within an file/standard input similar to 'grep' in Linux.

### PR DESCRIPTION
**Pull request by kalashjain23**
Solves #2 

Quick command hints:
`grep [pattern] [input]` (Standard input)
`grep [pattern] [file_name] -f` (Finding in a file)

### CODE REVIEW

**Comment by smv1999** [comment]
Your solution looks good to me @kalashjain23. But I am unable to merge because it has conflicts to be resolved. Could you please pull the remote changes first and then make your changes and push it ?

If you face any issues in this process, let me know !

**Comment by kalashjain23** [comment]
> Your solution looks good to me @kalashjain23. But I am unable to merge because it has conflicts to be resolved. Could you please pull the remote changes first and then make your changes and push it ?
> 
> If you face any issues in this process, let me know !

Hey! The merge conflict is now resolved!

**Review by smv1999 — APPROVED** [review]
Ok

**Comment by smv1999** [comment]
give @kalashjain23 150 points

**Comment by smv1999** [comment]
Great work @kalashjain23  !!!

**Comment by kalashjain23** [comment]
> Great work @kalashjain23 !!!

Thank you so much, sir!!
Do we have to wait for more issues to be listed on this repo, or we can contribute on any other repo (approved by SLOP 2.0) as well?

**Comment by smv1999** [comment]
You can create new issues on this repo and work on them too. I think you need to contact the Admin / Team of SLoP 2.0 regarding contributions to other repos.

**Pull request merged**
